local M = {}

local function bg(c, color)
	return c.transparent and "NONE" or color
end

function M.setup(p, opts)
	local c = vim.tbl_extend("force", p, { transparent = opts.transparent })

	return {
		-- Core editor UI
		Normal = { fg = c.fg1, bg = bg(c, c.bg0) },
		NormalNC = { fg = c.fg2, bg = bg(c, c.bg0) },
		NormalFloat = { fg = c.fg1, bg = bg(c, c.bg1) },
		FloatBorder = { fg = c.fg5, bg = bg(c, c.bg1) },
		FloatTitle = { fg = c.fern, bg = bg(c, c.bg1), bold = true },
		Cursor = { fg = c.bg0, bg = c.fg0 },
		CursorLine = { bg = bg(c, c.bg1) },
		CursorColumn = { link = "CursorLine" },
		ColorColumn = { bg = bg(c, c.bg1) },
		LineNr = { fg = c.fg5 },
		CursorLineNr = { fg = c.green, bold = true },
		SignColumn = { fg = c.fg4, bg = bg(c, c.bg0) },
		FoldColumn = { fg = c.fg5, bg = bg(c, c.bg0) },
		Folded = { fg = c.fg4, bg = bg(c, c.bg1), italic = true },
		Visual = { bg = c.bg3 },
		Search = { fg = c.bg0, bg = c.yellow },
		IncSearch = { fg = c.bg0, bg = c.orange, bold = true },
		CurSearch = { link = "IncSearch" },
		Substitute = { fg = c.bg0, bg = c.aqua, bold = true },
		MatchParen = { fg = c.aqua, bg = c.bg2, bold = true },
		NonText = { fg = c.bg4 },
		Whitespace = { fg = c.bg4 },
		SpecialKey = { fg = c.fg5 },
		Conceal = { fg = c.blue },
		Directory = { fg = c.teal, bold = true },
		Title = { fg = c.fern, bold = true },
		ErrorMsg = { fg = c.red, bold = true },
		WarningMsg = { fg = c.yellow, bold = true },
		MoreMsg = { fg = c.green },
		Question = { fg = c.aqua },
		ModeMsg = { fg = c.fg2, bold = true },
		MsgArea = { fg = c.fg1 },
		WinSeparator = { fg = c.bg4 },
		VertSplit = { link = "WinSeparator" },
		StatusLine = { fg = c.fg1, bg = bg(c, c.bg2) },
		StatusLineNC = { fg = c.fg4, bg = bg(c, c.bg1) },
		TabLine = { fg = c.fg4, bg = bg(c, c.bg1) },
		TabLineSel = { fg = c.fern, bg = bg(c, c.bg2), bold = true },
		TabLineFill = { bg = bg(c, c.bg0) },

		-- Menus and completion
		Pmenu = { fg = c.fg1, bg = bg(c, c.bg1) },
		PmenuSel = { fg = c.bg0, bg = c.teal, bold = true },
		PmenuSbar = { bg = bg(c, c.bg2) },
		PmenuThumb = { bg = c.bg4 },
		WildMenu = { fg = c.fern, bg = bg(c, c.bg1), bold = true },

		-- Classic syntax groups
		Comment = { fg = c.fg5, italic = opts.italics.comments },
		Constant = { fg = c.blue },
		String = { fg = c.moss },
		Character = { fg = c.aqua },
		Number = { fg = c.blue },
		Boolean = { fg = c.cyan, bold = true },
		Float = { link = "Number" },
		Identifier = { fg = c.fg1 },
		Function = { fg = c.teal, bold = opts.bold.functions },
		Statement = { fg = c.green },
		Conditional = { fg = c.green, italic = opts.italics.keywords },
		Repeat = { fg = c.green, italic = opts.italics.keywords },
		Label = { fg = c.aqua },
		Operator = { fg = c.fg3 },
		Keyword = { fg = c.green, italic = opts.italics.keywords },
		Exception = { fg = c.red },
		PreProc = { fg = c.aqua },
		Include = { fg = c.cyan },
		Define = { fg = c.aqua },
		Macro = { fg = c.aqua },
		PreCondit = { fg = c.aqua },
		Type = { fg = c.aqua, bold = opts.bold.types },
		StorageClass = { fg = c.green },
		Structure = { fg = c.aqua },
		Typedef = { fg = c.aqua },
		Special = { fg = c.cyan },
		SpecialChar = { fg = c.cyan },
		Tag = { fg = c.teal },
		Delimiter = { fg = c.fg4 },
		Debug = { fg = c.orange },
		Underlined = { fg = c.blue, underline = true },
		Bold = { bold = true },
		Italic = { italic = true },
		Error = { fg = c.red },
		Todo = { fg = c.bg0, bg = c.green, bold = true },

		-- Diagnostics
		DiagnosticError = { fg = c.red },
		DiagnosticWarn = { fg = c.yellow },
		DiagnosticInfo = { fg = c.blue },
		DiagnosticHint = { fg = c.green },
		DiagnosticOk = { fg = c.green },
		DiagnosticVirtualTextError = { fg = c.red, bg = bg(c, c.bg_red) },
		DiagnosticVirtualTextWarn = { fg = c.yellow, bg = bg(c, c.bg_yellow) },
		DiagnosticVirtualTextInfo = { fg = c.blue, bg = bg(c, c.bg_blue) },
		DiagnosticVirtualTextHint = { fg = c.green, bg = bg(c, c.bg_green) },
		DiagnosticUnderlineError = { sp = c.red, undercurl = true },
		DiagnosticUnderlineWarn = { sp = c.yellow, undercurl = true },
		DiagnosticUnderlineInfo = { sp = c.blue, undercurl = true },
		DiagnosticUnderlineHint = { sp = c.green, undercurl = true },
		DiagnosticFloatingError = { link = "DiagnosticError" },
		DiagnosticFloatingWarn = { link = "DiagnosticWarn" },
		DiagnosticFloatingInfo = { link = "DiagnosticInfo" },
		DiagnosticFloatingHint = { link = "DiagnosticHint" },
		DiagnosticSignError = { link = "DiagnosticError" },
		DiagnosticSignWarn = { link = "DiagnosticWarn" },
		DiagnosticSignInfo = { link = "DiagnosticInfo" },
		DiagnosticSignHint = { link = "DiagnosticHint" },

		-- Diffs and git signs
		DiffAdd = { fg = c.green, bg = bg(c, c.bg_green) },
		DiffChange = { fg = c.blue, bg = bg(c, c.bg_blue) },
		DiffDelete = { fg = c.red, bg = bg(c, c.bg_red) },
		DiffText = { fg = c.aqua, bg = bg(c, c.bg_blue), bold = true },
		Added = { fg = c.green },
		Changed = { fg = c.blue },
		Removed = { fg = c.red },
		GitSignsAdd = { fg = c.green },
		GitSignsChange = { fg = c.blue },
		GitSignsDelete = { fg = c.red },

		-- Treesitter captures
		["@comment"] = { link = "Comment" },
		["@string"] = { link = "String" },
		["@string.documentation"] = { fg = c.moss, italic = true },
		["@character"] = { link = "Character" },
		["@number"] = { link = "Number" },
		["@boolean"] = { link = "Boolean" },
		["@float"] = { link = "Float" },
		["@constant"] = { link = "Constant" },
		["@constant.builtin"] = { fg = c.cyan, bold = true },
		["@constant.macro"] = { fg = c.aqua },
		["@module"] = { fg = c.teal },
		["@label"] = { link = "Label" },
		["@variable"] = { fg = c.fg1 },
		["@variable.builtin"] = { fg = c.cyan, italic = true },
		["@variable.parameter"] = { fg = c.fg2 },
		["@variable.member"] = { fg = c.blue },
		["@property"] = { fg = c.blue },
		["@type"] = { link = "Type" },
		["@type.builtin"] = { fg = c.aqua, italic = true },
		["@attribute"] = { fg = c.fern },
		["@function"] = { link = "Function" },
		["@function.builtin"] = { fg = c.cyan },
		["@function.call"] = { fg = c.teal },
		["@function.method"] = { fg = c.teal },
		["@function.method.call"] = { fg = c.teal },
		["@constructor"] = { fg = c.aqua },
		["@keyword"] = { link = "Keyword" },
		["@keyword.function"] = { fg = c.green, italic = opts.italics.keywords },
		["@keyword.operator"] = { fg = c.green },
		["@keyword.return"] = { fg = c.green, italic = opts.italics.keywords },
		["@keyword.import"] = { fg = c.cyan },
		["@keyword.conditional"] = { link = "Conditional" },
		["@keyword.repeat"] = { link = "Repeat" },
		["@operator"] = { link = "Operator" },
		["@punctuation.delimiter"] = { link = "Delimiter" },
		["@punctuation.bracket"] = { fg = c.fg4 },
		["@punctuation.special"] = { fg = c.cyan },
		["@tag"] = { fg = c.teal },
		["@tag.attribute"] = { fg = c.aqua },
		["@tag.delimiter"] = { fg = c.fg4 },

		-- Common plugins in this config
		LspReferenceText = { bg = bg(c, c.bg2) },
		LspReferenceRead = { bg = bg(c, c.bg2) },
		LspReferenceWrite = { bg = bg(c, c.bg2) },
		BlinkCmpMenu = { link = "Pmenu" },
		BlinkCmpMenuSelection = { link = "PmenuSel" },
		BlinkCmpLabel = { fg = c.fg1 },
		BlinkCmpLabelMatch = { fg = c.green, bold = true },
		BlinkCmpKind = { fg = c.aqua },
		WhichKey = { fg = c.green },
		WhichKeyGroup = { fg = c.teal },
		WhichKeyDesc = { fg = c.fg1 },
		WhichKeySeparator = { fg = c.fg5 },
		WhichKeyFloat = { bg = bg(c, c.bg1) },
		MiniFilesDirectory = { fg = c.teal, bg = "NONE", bold = true },
		SnacksPickerFile = { fg = c.fg1, bg = "NONE" },
		SnacksDashboardHeader = { fg = c.fern, bold = true },
		SnacksDashboardIcon = { fg = c.teal },
		SnacksDashboardKey = { fg = c.aqua, bold = true },
		SnacksDashboardDesc = { fg = c.fg1 },
		SnacksDashboardFile = { fg = c.moss },
		SnacksDashboardDir = { fg = c.teal },
	}
end

return M
