local M = {}

local function bg(c, color)
	return c.transparent and "NONE" or color
end

function M.setup(p, opts)
	local c = vim.tbl_extend("force", p, { transparent = opts.transparent })

	return {
		-- LSP references
		LspReferenceText = { bg = bg(c, c.bg2) },
		LspReferenceRead = { bg = bg(c, c.bg2) },
		LspReferenceWrite = { bg = bg(c, c.bg2) },

		-- lazy.nvim
		LazyNormal = { fg = c.fg1, bg = bg(c, c.bg0) },
		LazyH1 = { fg = c.ochre_lighter, bold = true },
		LazyH2 = { fg = c.ochre_lighter, bold = true },
		LazyButton = { fg = c.fg2, bg = bg(c, c.bg2) },
		LazyButtonActive = { fg = c.bg0, bg = c.aqua, bold = true },
		LazySpecial = { fg = c.fern },
		LazyComment = { fg = c.fg5, italic = true },
		LazyDimmed = { fg = c.fg5 },
		LazyProp = { fg = c.fg4 },
		LazyValue = { fg = c.aqua },
		LazyUrl = { fg = c.teal, underline = true },
		LazyDir = { fg = c.cyan },
		LazyCommit = { fg = c.fern },
		LazyCommitIssue = { fg = c.purple },
		LazyCommitScope = { fg = c.fg4 },
		LazyReasonPlugin = { fg = c.cyan },
		LazyReasonStart = { fg = c.fern },
		LazyReasonEvent = { fg = c.aqua },
		LazyReasonKeys = { fg = c.fern },
		LazyReasonCmd = { fg = c.yellow },
		LazyReasonFt = { fg = c.cyan },
		LazyReasonImport = { fg = c.purple },
		LazyProgressDone = { fg = c.fern },
		LazyProgressTodo = { fg = c.bg4 },
		LazyNoCond = { fg = c.red },
		LazyTaskOutput = { fg = c.fg3 },

		-- Mason
		MasonNormal = { fg = c.fg1, bg = bg(c, c.bg0) },
		MasonHeader = { fg = c.ochre_lighter, bold = true },
		MasonHeaderSecondary = { fg = c.aqua, bold = true },
		MasonHighlight = { fg = c.fern },
		MasonHighlightBlock = { fg = c.bg0, bg = c.aqua },
		MasonHighlightBlockBold = { fg = c.bg0, bg = c.aqua, bold = true },
		MasonHighlightSecondary = { fg = c.cyan },
		MasonHighlightBlockSecondary = { fg = c.bg0, bg = c.cyan },
		MasonHighlightBlockBoldSecondary = { fg = c.bg0, bg = c.cyan, bold = true },
		MasonMuted = { fg = c.fg5 },
		MasonMutedBlock = { fg = c.fg3, bg = bg(c, c.bg2) },
		MasonMutedBlockBold = { fg = c.fg2, bg = bg(c, c.bg2), bold = true },
		MasonError = { fg = c.red },
		MasonWarning = { fg = c.yellow },

		-- Telescope, if installed later
		TelescopeNormal = { fg = c.fg1, bg = bg(c, c.bg0) },
		TelescopeBorder = { fg = c.bg4, bg = bg(c, c.bg0) },
		TelescopePromptNormal = { fg = c.fg1, bg = bg(c, c.bg1) },
		TelescopePromptBorder = { fg = c.aqua, bg = bg(c, c.bg1) },
		TelescopePromptTitle = { fg = c.ochre_lighter, bold = true },
		TelescopeResultsTitle = { fg = c.ochre_lighter, bold = true },
		TelescopePreviewTitle = { fg = c.ochre_lighter, bold = true },
		TelescopeSelection = { fg = c.fg0, bg = bg(c, c.bg2), bold = true },
		TelescopeMatching = { fg = c.fern, bold = true },

		-- Snacks picker/dashboard/notifier
		SnacksNormal = { fg = c.fg1, bg = bg(c, c.bg0) },
		SnacksPicker = { fg = c.fg1, bg = bg(c, c.bg0) },
		SnacksPickerBorder = { fg = c.bg4, bg = bg(c, c.bg0) },
		SnacksPickerTitle = { fg = c.ochre_lighter, bold = true },
		SnacksPickerInput = { fg = c.fg1, bg = bg(c, c.bg1) },
		SnacksPickerInputBorder = { fg = c.aqua, bg = bg(c, c.bg1) },
		SnacksPickerInputTitle = { fg = c.ochre_lighter, bold = true },
		SnacksPickerList = { fg = c.fg1, bg = bg(c, c.bg0) },
		SnacksPickerPreview = { fg = c.fg1, bg = bg(c, c.bg0) },
		SnacksPickerFile = { fg = c.fg1, bg = "NONE" },
		SnacksPickerDir = { fg = c.cyan },
		SnacksPickerPathHidden = { fg = c.fg5 },
		SnacksPickerPathIgnored = { fg = c.fg5, italic = true },
		SnacksPickerMatch = { fg = c.fern, bold = true },
		SnacksPickerSelected = { fg = c.fern, bold = true },
		SnacksPickerGitStatus = { fg = c.fg4 },
		SnacksPickerGitStatusAdded = { fg = c.fern },
		SnacksPickerGitStatusModified = { fg = c.teal },
		SnacksPickerGitStatusDeleted = { fg = c.red },
		SnacksDashboardHeader = { fg = c.ochre_lighter, bold = true },
		SnacksDashboardIcon = { fg = c.cyan },
		SnacksDashboardKey = { fg = c.aqua, bold = true },
		SnacksDashboardDesc = { fg = c.fg1 },
		SnacksDashboardFile = { fg = c.moss },
		SnacksDashboardDir = { fg = c.teal },
		SnacksNotifierInfo = { fg = c.cyan },
		SnacksNotifierWarn = { fg = c.yellow },
		SnacksNotifierError = { fg = c.red },
		SnacksNotifierDebug = { fg = c.fg5 },
		SnacksNotifierTrace = { fg = c.purple },

		-- Blink cmp
		BlinkCmpMenu = { link = "Pmenu" },
		BlinkCmpMenuBorder = { link = "FloatBorder" },
		BlinkCmpMenuSelection = { link = "PmenuSel" },
		BlinkCmpScrollBarThumb = { link = "PmenuThumb" },
		BlinkCmpScrollBarGutter = { link = "PmenuSbar" },
		BlinkCmpLabel = { fg = c.fg1 },
		BlinkCmpLabelDeprecated = { fg = c.fg5, strikethrough = true },
		BlinkCmpLabelMatch = { fg = c.fern, bold = true },
		BlinkCmpKind = { fg = c.aqua },
		BlinkCmpKindFunction = { fg = c.cyan },
		BlinkCmpKindMethod = { fg = c.cyan },
		BlinkCmpKindVariable = { fg = c.fg1 },
		BlinkCmpKindField = { fg = c.aqua },
		BlinkCmpKindProperty = { fg = c.aqua },
		BlinkCmpKindClass = { fg = c.fern },
		BlinkCmpKindInterface = { fg = c.fern },
		BlinkCmpKindModule = { fg = c.cyan },
		BlinkCmpKindKeyword = { fg = c.fern },
		BlinkCmpKindSnippet = { fg = c.orange },
		BlinkCmpKindText = { fg = c.fg2 },
		BlinkCmpSource = { fg = c.fg5 },
		BlinkCmpGhostText = { fg = c.fg5, italic = true },
		BlinkCmpDoc = { link = "NormalFloat" },
		BlinkCmpDocBorder = { link = "FloatBorder" },
		BlinkCmpSignatureHelp = { link = "NormalFloat" },
		BlinkCmpSignatureHelpBorder = { link = "FloatBorder" },

		-- which-key
		WhichKey = { fg = c.fern },
		WhichKeyGroup = { fg = c.cyan },
		WhichKeyDesc = { fg = c.fg1 },
		WhichKeySeparator = { fg = c.fg5 },
		WhichKeyFloat = { bg = bg(c, c.bg1) },
		WhichKeyBorder = { fg = c.bg4, bg = bg(c, c.bg1) },
		WhichKeyValue = { fg = c.fg4 },
		WhichKeyIcon = { fg = c.aqua },
		WhichKeyIconAzure = { fg = c.cyan },
		WhichKeyIconGreen = { fg = c.fern },
		WhichKeyIconOrange = { fg = c.orange },
		WhichKeyIconRed = { fg = c.red },
		WhichKeyIconYellow = { fg = c.yellow },

		-- noice.nvim / nvim-notify
		NoiceCmdline = { fg = c.fg1, bg = bg(c, c.bg1) },
		NoiceCmdlinePopup = { fg = c.fg1, bg = bg(c, c.bg1) },
		NoiceCmdlinePopupBorder = { fg = c.aqua, bg = bg(c, c.bg1) },
		NoiceCmdlinePopupTitle = { fg = c.ochre_lighter, bold = true },
		NoiceCmdlineIcon = { fg = c.aqua },
		NoicePopup = { link = "NormalFloat" },
		NoicePopupBorder = { link = "FloatBorder" },
		NoiceMini = { fg = c.fg2, bg = bg(c, c.bg1) },
		NoiceConfirm = { link = "NormalFloat" },
		NoiceConfirmBorder = { link = "FloatBorder" },
		NotifyERRORBorder = { fg = c.red },
		NotifyWARNBorder = { fg = c.yellow },
		NotifyINFOBorder = { fg = c.cyan },
		NotifyDEBUGBorder = { fg = c.fg5 },
		NotifyTRACEBorder = { fg = c.purple },
		NotifyERRORIcon = { fg = c.red },
		NotifyWARNIcon = { fg = c.yellow },
		NotifyINFOIcon = { fg = c.cyan },
		NotifyDEBUGIcon = { fg = c.fg5 },
		NotifyTRACEIcon = { fg = c.purple },
		NotifyERRORTitle = { fg = c.red, bold = true },
		NotifyWARNTitle = { fg = c.yellow, bold = true },
		NotifyINFOTitle = { fg = c.cyan, bold = true },
		NotifyDEBUGTitle = { fg = c.fg5, bold = true },
		NotifyTRACETitle = { fg = c.purple, bold = true },

		-- mini.nvim
		MiniFilesDirectory = { fg = c.teal, bg = "NONE", bold = true },
		MiniFilesFile = { fg = c.fg1 },
		MiniFilesBorder = { fg = c.bg4 },
		MiniFilesTitle = { fg = c.ochre_lighter, bold = true },
		MiniFilesTitleFocused = { fg = c.ochre_lighter, bold = true },
	}
end

return M
